AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless app

  Sample Serverless APIs

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMODB: "http://192.168.1.245:8009"

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri: ./flex
      Description: Provides the base backend shared library and dependencies
      LayerName: shared-layer

  CatalogAssetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/catalog/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api
          Properties:
            Path: /asset/{assetid}
            Method: get

  HelloV3Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/fast/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v3/hello
            Method: get

  CatalogFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/catalog/
      Handler: app.handler
      Timeout: 10
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        File:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /static/catalog/{file}
            Method: get

  HelloFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/fast/
      Handler: app.handler
      Timeout: 10
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        File:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /static/hello/{file}
            Method: get

  HelloV2Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/fast/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v2/hello
            Method: get

  HelloAPIDocsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10
      CodeUri: lambdas/fast/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello/docs
            Method: get

  CatalogAPIDocsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10
      CodeUri: lambdas/catalog/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /catalog/docs
            Method: get


  QuoteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/quote/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /quote
            Method: get

  WidgetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/widget/
      Handler: app.lambda_handler
      Layers:
        - !Ref SharedLayer
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Widget:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /widget
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WidgetApi:
    Description: "API Gateway endpoint URL for Prod stage for Widget function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/widget/"
  WidgetFunction:
    Description: "Widget Lambda Function ARN"
    Value: !GetAtt WidgetFunction.Arn
  WidgetFunctionIamRole:
    Description: "Implicit IAM Role created for Widget function"
    Value: !GetAtt WidgetFunctionRole.Arn

  QuoteApi:
    Description: "API Gateway endpoint URL for Prod stage for Quote function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quote/"
  QuoteFunction:
    Description: "Quote Lambda Function ARN"
    Value: !GetAtt QuoteFunction.Arn
  QuoteFunctionIamRole:
    Description: "Implicit IAM Role created for Quote function"
    Value: !GetAtt QuoteFunctionRole.Arn

  HelloFileApi:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/file/catalog"
  HelloFileFunction:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt HelloFileFunction.Arn
  HelloFileFunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt HelloFileFunctionRole.Arn

  CatalogFileApi:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/file/catalog"
  CatalogFileFunction:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt   CatalogFileFunction.Arn
  CatalogFileFunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt CatalogFileFunctionRole.Arn

  CatalogAssetApi:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/asset/"
  CatalogAssetFunction:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt CatalogAssetFunction.Arn
  CatalogAssetFunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt CatalogAssetFunctionRole.Arn

  HelloV2Api:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v2/hello/"
  HelloV2Function:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt HelloV2Function.Arn
  HelloV2FunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt HelloV2FunctionRole.Arn

  CatalogAPIDocsApi:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/catalog/docs"
  CatalogAPIDocsFunction:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt CatalogAPIDocsApiDocsFunction.Arn
  CatalogAPIDocsFunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt CatalogAPIDocsApiFunctionRole.Arn

  HelloAPIDocsApi:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/docs"
  HelloAPIDocsFunction:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt HelloAPIDocsApiDocsFunction.Arn
  HelloAPIDocsFunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt HelloAPIDocsApiFunctionRole.Arn

  HelloV3Api:
    Description: "API Gateway endpoint URL for Prod stage for Fast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v3/hello/"
  HelloV3Function:
    Description: "Fast Lambda Function ARN"
    Value: !GetAtt HelloV3Function.Arn
  HelloV3FunctionIamRole:
    Description: "Implicit IAM Role created for Fast function"
    Value: !GetAtt HelloV3FunctionRole.Arn